In [11]:
# Partition Equal Subset Sum

In [51]:


def canPartition(nums, l, target, memo = {}):
    canPartition.count += 1
    print(l , target, memo)
    key = "{},{}".format(l, target) 
    if key in memo:
        return memo[key]
    if l >= len(nums):
        memo[key] = False
        return False
    if target == 0:
        return True
    if target < 0: 
        memo[key] = False
        return False
    
    
    if canPartition(nums, l + 1, target - nums[l], memo) :
        memo[key] = True
        return True
    if canPartition(nums, l + 1, target, memo):
        memo[key] = True
        return True
    memo[key] = False
    return False
    


nums = [3,3,3,4,5]



canPartition.count = 0
print(canPartition(nums, 0, sum(nums) / 2))
canPartition.count

0 9.0 {}
1 6.0 {}
2 3.0 {}
3 0.0 {}
True


4

In [52]:
# 70. Climbing Stairs

In [3]:
def climbStairs(n: int, memo) -> int:
    if n in memo:
        return memo[n]
    
    result = climbStairs(n-1, memo ) + climbStairs(n-2, memo) 
    memo[n] = result
    del memo[n-2]
    return result

climbStairs(25, { 0: 1, 1:1})

121393

In [79]:
# 322. Coin Change

In [154]:
def coinChange(coins, amount, memo) -> int:
    coinChange.count += 1
#     print(amount, memo)
    if amount in memo:
        return memo[amount]
    
    min_d = float("inf")
    for n in coins:
        if n <= amount:
            min_d = min(min_d, coinChange(coins, amount - n, memo) + 1)
    
    memo[amount] = min_d
    return min_d
    
    
#     if coinChange.minDepth != float("inf") :
#     memo[amount] = coinChange.minDept
   

coins = [186,419,83,408]
amount = 6249

coinChange.count = 0
coins.sort(reverse=True)
memo = { 0: 1}


coinChange(coins, amount, memo)
print("minimum coins required: ", memo[amount] - 1 if amount in memo and memo[amount] != float("inf") else -1)
coinChange.count

minimum coins required:  20


17501

In [162]:
def lengthOfLIS(nums):
    LTS = [1] * len(nums)
    for i in range(len(nums) - 2, -1, -1):
        for j in range(i, len(nums)):
            if nums[i] < nums[j] :
                LTS[i] = max(LTS[i], LTS[j] + 1)
    return max(LTS)

nums = [0,1,0,3,2,3]

lengthOfLIS(nums)

4

In [209]:
def LCS_rec(text1, text2, i, j, memo):
    
#     print(memo)
    if i >= len(text1) or j >= len(text2):
        return 0
    key = "{}{}".format(i,j)
    if key in memo:
        return memo[key]
    LCS_rec.count += 1
    if text1[i] == text2[j]:
        cc = 1 + LCS_rec(text1, text2, i+1, j+1, memo)
        memo[key] = cc
        return cc
    else:
        cc = max(LCS_rec(text1, text2, i+1, j, memo), LCS_rec(text1, text2, i, j+1, memo))
        memo[key] = cc
        return cc


def longestCommonSubsequence(text1, text2):
    m = len(text1)
    n = len(text2)
    LCS_rec.count = 0
    memo = {}
    result = LCS_rec(text1, text2, 0 ,0, memo)
    print("memo length ", len(memo), m*n)
    return result



text1 = "oxcpqrsvwf"
text2 = "shmtulqrypy"
print("ans", longestCommonSubsequence(text1, text2))
LCS_rec.count

memo length  107 110
ans 2


107

In [210]:
# 139. Word Break

In [320]:
import pandas as pd 

def wordBreak(s, wordDict) -> bool:
    wordBreak.count  = 0
    wordDict = set(wordDict)
    dp =  [False] * (len(s))
        
    for i in range(len(s)):
        for j in range(i,len(s)):
            wordBreak.count += 1
            
            if s[i:j+1] in wordDict:
                l = j + 1 - i
                dp[j] = True if j-l < 0 else (dp[j-l] and True) or dp[j]
            
                print(s[i:j+1], dp[j],dp[j-l], i , j , l)
            if dp[j] :
                if len(s) - 1 == j:
                    return True
    print(dp)
    return False







s = "catsanddog"
wordDict =["cat","cats","and","sand","dog"]


print(wordBreak(s, wordDict))

print(wordBreak.count)

cat True False 0 2 3
cats True False 0 3 4
sand True True 3 6 4
and True True 4 6 3
dog True True 7 9 3
True
52


In [326]:
def wordBreak2(s, wordDict):
    output = []
    wb2(s, set(wordDict), 0, [], output)
    return output

def wb2(s, wordDict, p, stack , output):
    if p >= len(s) :
        output.append(" ".join(stack))
        return
    for i in range(p,len(s) ):
        wrd = s[p:i+1]
        if wrd in wordDict:
            stack.append(wrd)
            wb2(s, wordDict, i+1, stack, output)
            stack.pop()


s = "catsanddog"
wordDict =["cat","cats","and","sand","dog"]

print(wordBreak2(s, wordDict))

# print(wordBreak2.count)

['cat sand dog', 'cats and dog']


In [1]:
def combinationSum4(nums, target):
    memo = {}
    return cmb(nums, target, memo)

def cmb(nums, target, memo):
    if target < 0:
        return 0
    if target == 0:
        return 1
    if target in memo:
        return memo[target]
    s = 0
    for i in range(len(nums)):
        s += cmb(nums, target - nums[i], memo)
    memo[target] = s
    return s
        
        

nums = [1,2,4]
target = 12

print(combinationSum4(nums, target))


520


In [344]:
def rob(nums) -> int:
    rob1 = rob2 = 0
    for i in range(len(nums)):
        if i % 2 == 0:
            rob1 = max(rob1 + nums[i], rob2 )
        else:
            rob2 = max(rob1, rob2 + nums[i])
    return max(rob1, rob2)


nums = [2,7,9,3,1]
rob(nums)

12

In [430]:
def robCircle(nums) -> int:
    if len(nums) < 3:
        return max(nums)
    rob1 = rob2 = 0
    for i in range(len(nums) - 1):
        if i % 2 == 0:
            rob1 = max(rob1 + nums[i], rob2 )
        else:
            rob2 = max(rob1, rob2 + nums[i])
    m = max(rob1, rob2)
    rob1 = rob2 = 0
    for i in range(len(nums) - 1, 0, -1):
        if i % 2 == 0:
            rob1 = max(rob1 + nums[i], rob2 )
        else:
            rob2 = max(rob1, rob2 + nums[i])
    return max(rob1, rob2, m)

nums = [2,1,1,2]


robCircle(nums)

3

In [484]:


def numDecodings(s: str) -> int:
    return ndr(s,0, {})

def ndr(s, i, memo):
#     print( "i-", i)
    if i >= len(s):
        return 1
    
    if s[i] == "0":
        return 0
    
    if i in memo:
        return memo[i]
    
    r = ndr(s, i + 1, memo)
    
    if i+2 <= len(s) and int(s[i:i+2]) <= 26:
#         print( "s-", s[i:i+2], i)
        r += ndr(s, i + 2, memo)
            
    memo[i] = r
#     print( "r-", r, i)
    return r

    
    
    

s = "226"
numDecodings(s)

i- 0
i- 1
i- 2
i- 3
r- 1 2
s- 26 1
i- 3
r- 2 1
s- 22 0
i- 2
r- 3 0


3

In [501]:
def uniquePaths(m: int, n: int) -> int:
    dp = [ [-1] * m for _ in range(n) ]
    dp[n-1] = [1] * m
    dp[n-1][m-1] = 1
    
    for i in range(n-2, -1, -1):
        dp[i][m-1] = 1
        for j in range(m-2, -1, -1):
            if dp[i][j] == -1:
                u = dp[i+1][j] if i+1 <n else 0
                l = dp[i][j+1] if j+1 <m else 0
                dp[i][j] = u+l
            
    return dp[0][0]

m = 1
n = 1

uniquePaths(m, n)

1

In [14]:
def canJump(nums) -> bool:
    memo = {}
    return cnJmpHpl(nums, 0, memo) , print(memo)

def cnJmpHpl(nums, i, memo):
    if i >= len(nums):
        return True
    if i == len(nums) -1 and nums[i] == 0:
        return True
    if i in memo:
        return memo[i]
    for v in range(nums[i], 0, -1):
        if cnJmpHpl(nums, i+v, memo):
            memo[i] = True
            return True
    memo[i] = False
    return False

nums = [2,3,1,1,4]
canJump(nums)

{4: True, 3: True, 2: True, 0: True}


(True, None)

In [17]:
def canJump(nums) -> bool:
    i =0
    reachable = 0
    
    while i < len(nums) and i <= reachable:
        reachable = max(reachable, i + nums[i]  )
        i += 1
    return i == len(nums)

nums = [2,3,1,1,4]
canJump(nums)

True

In [26]:
def myPow( x: float, n: int) -> float:
    print(x, n)
    if n == 0:
        return 1
    if n < 0:
        return 1 / myPow(x, -n)
    if n % 2:
        return x * myPow(x, n - 1)
    return myPow(x * x, n / 2)

myPow(2,16)

2 16
4 8.0
16 4.0
256 2.0
65536 1.0
65536 0.0


65536

In [50]:
def mySqrt(n: int) -> int:
    if n <= 0:
        return 0
    sq = 1
    um = 9999
    while sq <= um:
        mid = sq + (um - sq) // 2
        if mid*mid <= n:
            sq = mid + 1
        else:
            um = mid - 1
    return sq - 1

mySqrt(64)

8

In [19]:
def climbStairs(n: int) -> int:
    a = b = 1
    for i in range(2, n + 1):
        c = a + b
        a = b
        b = c
    return c

n = 10
climbStairs(n)

89

In [4]:
def minCostClimbingStairs(cost) -> int:
    a = c = 0
    b = cost[-1]
    for i in range(len(cost) - 2, -1, -1):
        c = min(cost[i] + b, cost[i] + a)
        print( a, b, c)
        a = b
        b = c
    return min(a, b)

cost = [10, 15, 20]

minCostClimbingStairs(cost)

0 20 15
20 15 25


15

In [43]:

def howSum(target, nums, output, memo):
    if target in memo:
        return memo[target]
    if target == 0:
        return True
    if target < 0:
        return False
    
    for n in nums:
        result = howSum(target - n, nums, output , memo)
        if result:
            output.append(n)
            return True
        memo[target] = result
    return False




target = 7
nums = [2,3,4,7]
output = []
memo = {}
howSum(target, nums, output, memo)
print(output)
memo


[3, 2, 2]


{1: False, 3: False}

In [15]:
def bestSum(target, nums, memo):
    if target in memo:
        return memo[target]
    if target == 0:
        return []
    if target < 0:
        return None
    minS = float("inf")
    output = None
    for n in nums:
        if n == 0:
            continue
        bs = bestSum(target - n, nums, memo)
        if bs is not None and len(bs) + 1 < minS:
            output = []
            output.extend(bs)
            output.append(n)
            minS = min(minS, len(output) )
    memo[target] = output
    return output

target = 2500
nums = [i for i in range(0, 500, 50)]
memo = {}
output = bestSum(target, nums, memo)
print(output)
print(memo)


[450, 450, 450, 450, 450, 250]
{50: [50], 100: [100], 150: [150], 200: [200], 250: [250], 300: [300], 350: [350], 400: [400], 450: [450], 500: [450, 50], 550: [450, 100], 600: [450, 150], 650: [450, 200], 700: [450, 250], 750: [450, 300], 800: [450, 350], 850: [450, 400], 900: [450, 450], 950: [450, 450, 50], 1000: [450, 450, 100], 1050: [450, 450, 150], 1100: [450, 450, 200], 1150: [450, 450, 250], 1200: [450, 450, 300], 1250: [450, 450, 350], 1300: [450, 450, 400], 1350: [450, 450, 450], 1400: [450, 450, 450, 50], 1450: [450, 450, 450, 100], 1500: [450, 450, 450, 150], 1550: [450, 450, 450, 200], 1600: [450, 450, 450, 250], 1650: [450, 450, 450, 300], 1700: [450, 450, 450, 350], 1750: [450, 450, 450, 400], 1800: [450, 450, 450, 450], 1850: [450, 450, 450, 450, 50], 1900: [450, 450, 450, 450, 100], 1950: [450, 450, 450, 450, 150], 2000: [450, 450, 450, 450, 200], 2050: [450, 450, 450, 450, 250], 2100: [450, 450, 450, 450, 300], 2150: [450, 450, 450, 450, 350], 2200: [450, 450, 450, 45

In [23]:
def canSum(target, nums):
    dp = [False]*(target + 1)
    dp[0] = True
    for i in range(target+1):
        if dp[i]:
            for n in nums:
                if i+n <= target:
                    dp[i+n] = True
    print(dp)
    return dp[target]

target = 14
nums = [2,3,4,7]
canSum(target, nums)

[True, False, True, True, True, True, True, True, True, True, True, True, True, True, True]


True

In [38]:
from collections import defaultdict
def bestSum(target, nums):
    dp = [False] * (target + 1)
    hp = defaultdict(list)
    dp[0] = True
    for i in range(target+1):
        if dp[i]:
            for n in nums:
                if n == 0: continue
                if i+n <= target:
                    dp[i+n] = True
                    if len(hp[i+n]) <= 0 or len(hp[i]) + 1 < len(hp[i+n]):
                        hp[i+n] = [n]
                        hp[i+n].extend(hp[i])
    print(hp)
    return hp[target]

target = 2501
nums = [i for i in range(0, 500, 50)]
bestSum(target, nums)

defaultdict(<class 'list'>, {50: [50], 0: [], 100: [100], 150: [150], 200: [200], 250: [250], 300: [300], 350: [350], 400: [400], 450: [450], 500: [450, 50], 550: [450, 100], 600: [450, 150], 650: [450, 200], 700: [450, 250], 750: [450, 300], 800: [450, 350], 850: [450, 400], 900: [450, 450], 950: [450, 450, 50], 1000: [450, 450, 100], 1050: [450, 450, 150], 1100: [450, 450, 200], 1150: [450, 450, 250], 1200: [450, 450, 300], 1250: [450, 450, 350], 1300: [450, 450, 400], 1350: [450, 450, 450], 1400: [450, 450, 450, 50], 1450: [450, 450, 450, 100], 1500: [450, 450, 450, 150], 1550: [450, 450, 450, 200], 1600: [450, 450, 450, 250], 1650: [450, 450, 450, 300], 1700: [450, 450, 450, 350], 1750: [450, 450, 450, 400], 1800: [450, 450, 450, 450], 1850: [450, 450, 450, 450, 50], 1900: [450, 450, 450, 450, 100], 1950: [450, 450, 450, 450, 150], 2000: [450, 450, 450, 450, 200], 2050: [450, 450, 450, 450, 250], 2100: [450, 450, 450, 450, 300], 2150: [450, 450, 450, 450, 350], 2200: [450, 450, 450

[]

In [55]:
def recursion(nums, i, memo):
    if i in memo:
        return memo[i]
    if i >= len(nums):
        return 0
    r = max(recursion(nums, i + 2, memo) + nums[i] , recursion(nums, i + 3, memo) + nums[i])
    memo[i] = r
    return r

def rob(nums) -> int:
    memo = {}
    return max(recursion(nums, 0, memo), recursion(nums, 1, memo))

def rob(nums) -> int:
    
    dp2 = dp3 = dp1 = dp = 0
    for i in range(len(nums) - 1, -1, -1):
        dp = max(dp3,dp2) + nums[i]
        dp3 = dp2
        dp2 = dp1
        dp1 = dp
        print(dp, dp2, dp3)
    
    return max(dp, dp2)
        

nums = [1,2]

rob(nums)

2 0 0
1 2 0


2

In [68]:
import numpy as np

def longestPalindrome(s) -> str:
    dp = [ [0] * len(s) for i in range(len(s)) ]
    maxLength = 0
    maxIndex = [0,1]
    for i in range(len(s) - 1, -1, -1):
        for j in range(i, len(s)):
            if i == j :
                dp[i][j] = 1
                if j > 0:
                    dp[i][j-1] = 1
            else:
                if s[i] == s[j] and dp[i+1][j-1]:
                    dp[i][j] = 1
                    length = abs(i - j) + 1
                    if maxLength < length:
                        maxLength = length
                        maxIndex = [i, j + 1]
    print(np.array(dp))
    return s[maxIndex[0]: maxIndex[1]]

s = "cbbd"
longestPalindrome(s) 


[[1 0 0 0]
 [1 1 1 0]
 [0 1 1 0]
 [0 0 1 1]]


'bb'

In [71]:
def countSubstrings(s) -> str:
    dp = [ [0] * len(s) for i in range(len(s)) ]
    count = 0
    for i in range(len(s) - 1, -1, -1):
        for j in range(i, len(s)):
            if i == j :
                count += 1
                dp[i][j] = 1
                if j > 0:
                    dp[i][j-1] = 1
            else:
                if s[i] == s[j] and dp[i+1][j-1]:
                    dp[i][j] = 1
                    count += 1
    print(np.array(dp))
    return count

s = "aaa"
countSubstrings(s) 

[[1 1 1]
 [1 1 1]
 [0 1 1]]


6

In [154]:



def ndr(s, i, memo):
#     print( "i-", i)
    if i >= len(s):
        return 1
    
    if s[i] == "0":
        return 0
    
    if i in memo:
        return memo[i]
    
    r = ndr(s, i + 1, memo)
    
    if i+2 <= len(s) and int(s[i:i+2]) <= 26:
        r += ndr(s, i + 2, memo)
            
    memo[i] = r
    return r

def numDecodings(s) -> int:
    dp = [0] * (len(s) + 2)
    dp[-2] = 1
    for i in range(len(s) - 1, -1 , -1):
        if s[i] == "0":
            continue
        if int(s[i:i+2]) <= 26 :
            dp[i] = dp[i+1] + dp[i+2]
        else:
            dp[i] = dp[i+1]
    print(dp)
    return dp[0]

s = "1201234"


ndr(s, 0, {}) == numDecodings(s)



[3, 3, 0, 3, 2, 1, 1, 1, 0]


True

In [15]:
def coinChangeRecursive(coins, amount, memo) -> int:
    if amount <= 0:
        return 0
    if amount in memo:
        return memo[amount]
    minDenomination = -1 
    for coin in coins:
        denominations = coinChangeRecursive(coins, amount - coin, memo)
        if denominations != -1:
            if minDenomination != -1:
                minDenomination = min(minDenomination, denominations + 1)
            else:
                minDenomination = denominations + 1
    memo[amount] = minDenomination
    return minDenomination

from collections import defaultdict, deque

def coinChangeDp(coins, amount):
    if len(coins) <= 0:
        return -1
    if amount <= 0:
        return 0
    dp = defaultdict(lambda : float("inf"))
    coins = set(coins)
    queue = deque([0])
    visited = set()
    while len(queue) > 0:
        k = queue.popleft()
        for coin in coins:
            if k+coin in coins:
                dp[k+coin] = 1
            else:
                dp[k+coin] = min(dp[k] + 1, dp[k+coin])
            if k+coin < amount and k+coin not in visited:
                queue.append(k+coin)
                visited.add(k+coin)
    print(len(dp),len(visited))
    return dp[amount] if amount in dp and dp[amount] != float("inf") else -1



coins = [25,50]
amount = 100
memo = {}
print(coinChangeRecursive(coins, amount, memo))
print(coinChangeDp(coins, amount))

2
5 3
2


In [72]:
def wordBreak(s, wordDict) -> bool:
    wordDict = set(wordDict)
    dp = [False] * (len(s) + 1)
    dp[-1] = True
    for i in range(len(s) - 1 , -1, -1):
        for j in range(i, -1, -1 ):
            if s[j:i+1] in wordDict:
                l = abs(i-j) + 1
                dp[j] = True and dp[j+l] or dp[j]
#                 print(dp, j, l,s[j:i+1] )
    return dp[0]


s = "aaaaaaa"
wordDict = ["aaaa","aaa"]
wordBreak(s, wordDict)

True

In [89]:
def lengthOfLIS(nums) -> int:
    dp = [1] * len(nums)
    for i in range(len(nums) -1, -1, -1):
        for j in range(i+1, len(nums)):
            if nums[i] < nums[j]:
                dp[i] = max(dp[i], dp[j] + 1)
    return max(dp)

nums = [4,10,4,3,8,9]
lengthOfLIS(nums)

[3, 1, 3, 3, 2, 1]


3

In [93]:
def canPartition(nums) -> bool:
    target = sum(nums) // 2
    dp = set([0])
    for i in range(len(nums) -1, -1, -1):
        v = set()
        for t in dp:
            if t == target:
                return True
            v.add(t)
            v.add(t + nums[i])
        dp = v
    return target in dp


nums = [1,5,11,5]
canPartition(nums)

True

In [100]:
def howPartition(nums) -> bool:
    target = sum(nums) // 2
    dp = { 0: [] }
    for i in range(len(nums) -1, -1, -1):
        v = {}
        for t in dp:
            v[t] = dp[t]
            v[t + nums[i]] = []
            v[t + nums[i]].extend(dp[t])
            v[t + nums[i]].append(nums[i])
        dp = v
    print(dp)
    return dp[target]


nums = [1,5,11,5]
howPartition(nums)

{0: [], 1: [1], 5: [5], 6: [5, 1], 11: [5, 5, 1], 12: [11, 1], 16: [5, 11], 17: [5, 11, 1], 10: [5, 5], 21: [5, 11, 5], 22: [5, 11, 5, 1]}


[5, 5, 1]

In [104]:
def bestPartition(nums) -> bool:
    target = sum(nums) // 2
    dp = { 0: [] }
    for i in range(len(nums) -1, -1, -1):
        v = {}
        for t in dp:
            v[t] = dp[t]
            ns = t + nums[i]
            if ns not in dp or len(dp[t]) + 1 < len(dp[ns]):
                v[ns] = []
                v[ns].extend(dp[t])
                v[ns].append(nums[i])
        dp = v
    print(dp)
    return dp[target]


nums = [1,5,11,5]
bestPartition(nums)

{0: [], 1: [1], 11: [11], 12: [11, 1], 5: [5], 6: [5, 1], 10: [5, 5], 16: [5, 11], 17: [5, 11, 1], 21: [5, 11, 5], 22: [5, 11, 5, 1]}


[11]

In [9]:
def rob(nums) -> int:
    dp1 = dp2 = dp3 = 0
    for i in range(len(nums)):
        dp = max(dp2, dp3) + nums[i]
        dp3 = dp2
        dp2 = dp1
        dp1 = dp
    return max(dp1,dp2)


nums = [1,2,3,1]
rob(nums)

4

In [13]:
def rob(nums) -> int:
    if len(nums) < 3:
        return max(nums)
    dp1 = dp2 = dp3 = 0
    for i in range(len(nums)-1):
        dp = max(dp2, dp3) + nums[i]
        dp3 = dp2
        dp2 = dp1
        dp1 = dp
    m = max(dp1, dp2)
    dp1 = dp2 = dp3 = 0
    for i in range(1, len(nums)):
        dp = max(dp2, dp3) + nums[i]
        dp3 = dp2
        dp2 = dp1
        dp1 = dp
    return max(dp1, dp2, m)

nums = [1,2,3,1]
rob(nums)

4

In [26]:
def coinChange(coins, amount: int) -> int:
    dp = [float("inf")] * (amount + 1)
    dp[0] = 0
    for i in range(amount + 1):
        for coin in coins:
            if i+coin < amount + 1:
                dp[i+coin] = min(dp[i+coin], dp[i] + 1)
    print(dp)
    return -1 if dp[amount] == float("inf") else dp[amount]
    pass

coins = [1,2,5]
amount = 11
coinChange(coins, amount)

[0, 1, 1, 2, 2, 1, 2, 2, 3, 3, 2, 3]


3

In [32]:
def longestCommonSubsequence(text1: str, text2: str) -> int:
    dp = [ [0]* (len(text2) + 1) for i in range(len(text1)+1) ]
    for i in range(len(text1) - 1, -1, -1 ):
        for j in range(len(text2) - 1, -1, -1 ):
            if text1[i] == text2[j]:
                dp[i][j] = dp[i+1][j+1] + 1
            else:
                dp[i][j] = max(dp[i+1][j],dp[i][j+1])
    print(dp)
    return dp[0][0]
    pass


text1 = "abcde"
text2 = "ace" 
longestCommonSubsequence(text1,text2)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[3, 2, 1, 0], [2, 2, 1, 0], [2, 2, 1, 0], [1, 1, 1, 0], [1, 1, 1, 0], [0, 0, 0, 0]]


3

In [2]:
from typing import List

def maxProfit(prices: List[int]) -> int:
    memo = {}
    def rec(i, prev):
        if i >= len(prices):
            return 0
        if (i,prev) in memo:
            return memo[(i,prev)]
            pass
        if prev == "C":
            pb = rec(i+1, "B") - prices[i]
            pc = rec(i+1, "C")
        elif prev == "B":
            pb = rec(i+1, "S") + prices[i]
            pc = rec(i+1, "B")
        else:
            pb = pc = rec(i+1, "C")
        print(i, prev, pb, pc)
        memo[(i,prev)] = max(pb, pc)
        return memo[(i,prev)]
    
    return rec(0, "C")
    pass

prices = [1,2,3,0,2]

maxProfit(prices)

4 B 2 0
4 C -2 0
3 C 2 0
2 S 2 2
3 S 0 0
4 S 0 0
3 B 0 2
2 B 3 2
1 B 4 3
2 C -1 2
1 C 1 2
0 C 3 2


3

In [27]:
def change(amount: int, coins: List[int]) -> int:
    memo = {}
    def rec(amt, i):
        if amt < 0 :
            return 0
        if amt == 0:
            return 1
        if (amt,i) in memo:
            return memo[(amt,i)]
            pass
        now = 0
        for j in range(i, len(coins)):
            now += rec(amt - coins[j], j)
        memo[(amt,i)] = now
        return now
        pass
    ans = rec(amount, 0)
    print(memo)
    return ans

amount = 5
coins = [1,2,5]
change(amount, coins)

{(1, 0): 1} 1
{(1, 0): 1, (2, 0): 2} 2
{(1, 0): 1, (2, 0): 2, (1, 1): 0} 1
{(1, 0): 1, (2, 0): 2, (1, 1): 0, (3, 0): 2} 3
{(1, 0): 1, (2, 0): 2, (1, 1): 0, (3, 0): 2, (2, 1): 1} 2
{(1, 0): 1, (2, 0): 2, (1, 1): 0, (3, 0): 2, (2, 1): 1, (4, 0): 3} 4
{(1, 0): 1, (2, 0): 2, (1, 1): 0, (3, 0): 2, (2, 1): 1, (4, 0): 3, (3, 1): 0} 3
{(1, 0): 1, (2, 0): 2, (1, 1): 0, (3, 0): 2, (2, 1): 1, (4, 0): 3, (3, 1): 0, (5, 0): 4} 5
{(1, 0): 1, (2, 0): 2, (1, 1): 0, (3, 0): 2, (2, 1): 1, (4, 0): 3, (3, 1): 0, (5, 0): 4}


4

In [29]:
def findTargetSumWays(nums: List[int], target: int) -> int:
    memo = {}
    def dfs(i,total):
        if i >= len(nums):
            if total == target:
                return 1
            else:
                return 0
        if (i,total) in memo:
            return memo[(i,total)]
        ways = dfs(i+1, total + nums[i] )
        ways += dfs(i+1, total - nums[i] )
        memo[(i,total)] = ways
        return ways
    return dfs(0,0)
    pass


nums = [1,1,1,1,1]
target = 3
findTargetSumWays(nums, target)

5

In [57]:
def isInterleave(s1: str, s2: str, s3: str) -> bool:
    if len(s3) != len(s1) + len(s2):
        return False
    if len(s1) <= 0:
        return s3 == s2
    if len(s2) <= 0:
        return s3 == s1
    memo = {}
    def recursion(i,j):
        k = i + j
        if k >= len(s3):
            memo[(i,j)] = True
            return True
        if (i,j) in memo:
            return memo[(i,j)]
        if i >= len(s1):
            memo[(i,j)] = s3[k:] == s2[j:]
            return memo[(i,j)]
        if j >= len(s2):
            memo[(i,j)] = s3[k:] == s1[i:]
            return memo[(i,j)]
        if s1[i] == s2[j]:
            if s3[k] == s1[i]:
                ans = recursion(i+1, j) or recursion(i, j+1)
            else:
                ans = False
            memo[(i,j)] = ans
            return ans
        if s2[j] == s3[k]:
            memo[(i,j)] = recursion(i, j+1)
            return memo[(i,j)]
        elif s1[i] == s3[k]:
            memo[(i,j)] = recursion(i+1, j)
            return memo[(i,j)]
        else:
            memo[(i,j)] = False
            return False
    return recursion(0,0)
    pass


s1 = "bbbbbabbbbabaababaaaabbababbaaabbabbaaabaaaaababbbababbbbbabbbbababbabaabababbbaabababababbbaaababaa"
s2 = "babaaaabbababbbabbbbaabaabbaabbbbaabaaabaababaaaabaaabbaaabaaaabaabaabbbbbbbbbbbabaaabbababbabbabaab"
s3 = "babbbabbbaaabbababbbbababaabbabaabaaabbbbabbbaaabbbaaaaabbbbaabbaaabababbaaaaaabababbababaababbababbbababbbbaaaabaabbabbaaaaabbabbaaaabbbaabaaabaababaababbaaabbbbbabbbbaabbabaabbbbabaaabbababbabbabbab"

isInterleave(s1,s2,s3)

False

In [55]:
import numpy as np

def numDistinct(s: str, t: str) -> int:
    memo = {}
    def dfs(i, j):
        dfs.count += 1
        if j > len(s):
            return 0
        if i >= len(t):
            return 1
        if (i,j) in memo:
            return memo[(i,j)]
        matchCount = 0
        for chi in range(j, len(s)):
            if t[i] == s[chi]:
                matchCount += dfs(i + 1, chi + 1)
        memo[(i,j)] = matchCount
        return matchCount
    dfs.count = 0
    ans = dfs(0,0)
    print(dfs.count)
    return ans
    pass

def numDistinct(s: str, t: str) -> int:
    dp = [ [0] * (len(s)+1) for _ in range(len(t)+1)]
    
    for i in range(len(s)+1):
        dp[len(t)][i] = 1
    
    for i in range(len(t)-1,-1,-1):
        for j in range(len(s)-1,-1,-1):
            if t[i] == s[j]:
                dp[i][j] = dp[i][j+1] + dp[i+1][j+1]
            else:
                dp[i][j] = dp[i][j+1]
    print(np.array(dp))
    return dp[0][0]

s = "rabbbit"
t = "rabbit"
numDistinct(s,t)

[[3 0 0 0 0 0 0 0]
 [3 3 0 0 0 0 0 0]
 [3 3 3 1 0 0 0 0]
 [3 3 3 2 1 0 0 0]
 [1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1]]


3