In [1]:
# Set Matrix Zeroes

In [11]:

def setZeroes(matrix) -> None:
    row_flag = False
    col_flag = False
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if i == 0 and matrix[i][j] == 0 :
                row_flag = True
                     
            if j == 0 and matrix[i][j] == 0 :
                col_flag = True
             
            if matrix[i][j] == 0 :
                matrix[0][j] = 0
                matrix[i][0] = 0
    print(row_flag, col_flag)
                
    for i in range(1,len(matrix)):
        for j in range(1,len(matrix[i])):
            if matrix[0][j] == 0 or matrix[i][0] == 0:
                matrix[i][j] = 0
    
    if row_flag :
        for i in range(len(matrix[0])) :
            matrix[0][i] = 0
    
    # modify first col if there was any 1
    if col_flag:
        for i in range(len(matrix)) :
            matrix[i][0] = 0
                
                
    return matrix




matrix = [[0,1]]

setZeroes(matrix)

True True
0 0
0 1


[[0, 0]]

In [12]:
# Spiral Matrix

In [22]:
def sprial(matrix, rowIndex, columnIndex, rowCount, columnCount, output):
    print(rowIndex, columnIndex, rowCount, columnCount, output)
    
    if rowCount < 1 and columnCount < 1:
        return
    
    if rowCount > 0:
        for j in range(columnIndex, columnIndex + columnCount):
            output.append(matrix[rowIndex][j])
        
    lastColumnIndex = columnIndex + columnCount - 1
    
    if columnCount > 0:
        for i in range(rowIndex + 1, rowIndex + rowCount):
            output.append(matrix[i][lastColumnIndex])
    
    lastRowIndex = rowIndex + rowCount - 1
    if rowIndex < lastRowIndex :
        for j in range(lastColumnIndex - 1, columnIndex - 1 , -1 ):
            output.append(matrix[lastRowIndex][j])
    
    if columnIndex < lastColumnIndex:
        for i in range(lastRowIndex - 1, rowIndex, -1):
            output.append(matrix[i][columnIndex])
        
    sprial(matrix, rowIndex + 1, columnIndex + 1,  rowCount - 2, columnCount- 2, output)

def spiralOrder(matrix):
    output = []
    
    sprial(matrix, 0,0, len(matrix), len(matrix[0]),output )
    return output

matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(spiralOrder(matrix))

matrix = [[1,2,3,4,5,6,7,8,9,10]]
print(spiralOrder(matrix))

matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
spiralOrder(matrix)

0 0 3 3 []
1 1 1 1 [1, 2, 3, 6, 9, 8, 7, 4]
2 2 -1 -1 [1, 2, 3, 6, 9, 8, 7, 4, 5]
[1, 2, 3, 6, 9, 8, 7, 4, 5]
0 0 1 10 []
1 1 -1 8 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
2 2 -3 6 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
3 3 -5 4 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
4 4 -7 2 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
5 5 -9 0 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
0 0 3 4 []
1 1 1 2 [1, 2, 3, 4, 8, 12, 11, 10, 9, 5]
2 2 -1 0 [1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]


[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]

In [23]:
# Rotate Image

In [58]:
import numpy as np

def rotate(matrix, rowIndex, columnIndex, rowCount, columnCount):
    
    if rowCount < 1 or columnCount < 1:
        return
    
    lastRowIndex = rowIndex + rowCount - 1
    lastColIndex = columnIndex + columnCount - 1
    
    for i in range(columnCount - 1):
        t = matrix[rowIndex][columnIndex + i]
        matrix[rowIndex][columnIndex + i] = matrix[lastRowIndex - i][columnIndex]
        matrix[lastRowIndex - i][columnIndex] =  matrix[lastRowIndex][lastColIndex - i]
        matrix[lastRowIndex][lastColIndex - i] =  matrix[rowIndex+i][lastColIndex]
        matrix[rowIndex + i][lastColIndex] = t
    
    print(rowIndex, columnIndex, rowCount, columnCount, lastRowIndex, lastColIndex)
    
    rotate(matrix, rowIndex +1, columnIndex + 1, rowCount - 2,  columnCount - 2)


def rotateBy90(matrix) -> None:
    rotate(matrix, 0 , 0, len(matrix), len(matrix) )
    return matrix

matrix =[[2,29,20,26,16,28],[12,27,9,25,13,21],[32,33,32,2,28,14],[13,14,32,27,22,26],[33,1,20,7,21,7],[4,24,1,6,32,34]]

print(np.array(matrix))

np.array(rotateBy90(matrix))


[[ 2 29 20 26 16 28]
 [12 27  9 25 13 21]
 [32 33 32  2 28 14]
 [13 14 32 27 22 26]
 [33  1 20  7 21  7]
 [ 4 24  1  6 32 34]]
0 0 6 6 5 5
1 1 4 4 4 4
2 2 2 2 3 3


array([[ 4, 33, 13, 32, 12,  2],
       [24,  1, 14, 33, 27, 29],
       [ 1, 20, 32, 32,  9, 20],
       [ 6,  7, 27,  2, 25, 26],
       [32, 21, 22, 28, 13, 16],
       [34,  7, 26, 14, 21, 28]])